// Discussion
const FETCH_DISCUSSIONS = 'FETCH_DISCUSSIONS';
const FETCH_DISCUSSION_BY_ID = 'FETCH_DISCUSSIONS_BY_ID';

// Profile
const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

// Posts
const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
const GET_POSTS_FAIL = 'GET_POSTS_FAIL';

const GET_POSTS_BY_ID_REQUEST = 'GET_POSTS_BY_ID_REQUEST';
const GET_POSTS_BY_ID_SUCCESS = 'GET_POSTS_BY_ID_SUCCESS';
const GET_POSTS_BY_ID_FAIL = 'GET_POSTS_BY_ID_FAIL';

const GET_POSTS_BY_USER_REQUEST = 'GET_POSTS_BY_USER_REQUEST';
const GET_POSTS_BY_USER_SUCCESS = 'GET_POSTS_BY_USER_SUCCESS';
const GET_POSTS_BY_USER_FAIL = 'GET_POSTS_BY_USER_FAIL';

const GET_POSTS_BY_DISCUSSION_REQUEST = 'GET_POSTS_BY_DISCUSSION_REQUEST';
const GET_POSTS_BY_DISCUSSION_SUCCESS = 'GET_POSTS_BY_DISCUSSION_SUCCESS';
const GET_POSTS_BY_DISCUSSION_FAIL = 'GET_POSTS_BY_DISCUSSION_FAIL';

export {
  FETCH_DISCUSSIONS,
  FETCH_DISCUSSION_BY_ID,
  USER_DETAILS_REQUEST,
  USER_DETAILS_SUCCESS,
  USER_DETAILS_FAIL,
  USER_DETAILS_RESET,
  GET_POSTS_REQUEST,
  GET_POSTS_SUCCESS,
  GET_POSTS_FAIL,
  GET_POSTS_BY_ID_REQUEST,
  GET_POSTS_BY_ID_SUCCESS,
  GET_POSTS_BY_ID_FAIL,
  GET_POSTS_BY_USER_REQUEST,
  GET_POSTS_BY_USER_SUCCESS,
  GET_POSTS_BY_USER_FAIL,
  GET_POSTS_BY_DISCUSSION_REQUEST,
  GET_POSTS_BY_DISCUSSION_SUCCESS,
  GET_POSTS_BY_DISCUSSION_FAIL,
};
