// Discussion
const FETCH_DISCUSSIONS = 'FETCH_DISCUSSIONS';
const FETCH_DISCUSSION_BY_ID = 'FETCH_DISCUSSIONS_BY_ID';

// Profile
const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export {
  FETCH_DISCUSSIONS,
  FETCH_DISCUSSION_BY_ID,
  USER_DETAILS_REQUEST,
  USER_DETAILS_SUCCESS,
  USER_DETAILS_FAIL,
  USER_DETAILS_RESET,
};
