// Notifications
const GET_NOTIFICATIONS_BY_USER_REQUEST = 'GET_NOTIFICATIONS_BY_USER_REQUEST';
const GET_NOTIFICATIONS_BY_USER_SUCCESS = 'GET_NOTIFICATIONS_BY_USER_SUCCESS';
const GET_NOTIFICATIONS_BY_USER_FAIL = 'GET_NOTIFICATIONS_BY_USER_FAIL';

const GET_NOTIFICATION_BY_ID_REQUEST = 'GET_NOTIFICATION_BY_ID_REQUEST';
const GET_NOTIFICATION_BY_ID_SUCCESS = 'GET_NOTIFICATION_BY_ID_SUCCESS';
const GET_NOTIFICATION_BY_ID_FAIL = 'GET_NOTIFICATION_BY_ID_FAIL';

const UPDATE_NOTIFICATION_REQUEST = 'UPDATE_NOTIFICATION_REQUEST';
const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS';
const UPDATE_NOTIFICATION_FAIL = 'UPDATE_NOTIFICATION_FAIL';

const DELETE_NOTIFICATION_BY_ID_REQUEST = 'DELETE_NOTIFICATION_BY_ID_REQUEST';
const DELETE_NOTIFICATION_BY_ID_SUCCESS = 'DELETE_NOTIFICATION_BY_ID_SUCCESS';
const DELETE_NOTIFICATION_BY_ID_FAIL = 'DELETE_NOTIFICATION_BY_ID_FAIL';

// Profile
const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export {
  USER_DETAILS_REQUEST,
  USER_DETAILS_SUCCESS,
  USER_DETAILS_FAIL,
  USER_DETAILS_RESET,
  GET_NOTIFICATIONS_BY_USER_REQUEST,
  GET_NOTIFICATIONS_BY_USER_SUCCESS,
  GET_NOTIFICATIONS_BY_USER_FAIL,
  GET_NOTIFICATION_BY_ID_REQUEST,
  GET_NOTIFICATION_BY_ID_SUCCESS,
  GET_NOTIFICATION_BY_ID_FAIL,
  UPDATE_NOTIFICATION_REQUEST,
  UPDATE_NOTIFICATION_SUCCESS,
  UPDATE_NOTIFICATION_FAIL,
  DELETE_NOTIFICATION_BY_ID_REQUEST,
  DELETE_NOTIFICATION_BY_ID_SUCCESS,
  DELETE_NOTIFICATION_BY_ID_FAIL,
};
